## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "github_dark"

# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
add_newline = true 

# Prompt symbols 
[character]
success_symbol = "[●](green bold)"
error_symbol = "[○](red)"

[directory]
format = "[]($style)[  ](bg:base fg:blue)[$path](bg:base fg:text bold)[ ]($style)"
style = "bg:none fg:base"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[  ](bg:base fg:green bold)$branch](bg:base fg:text)[ ]($style)"
style = "bg:none fg:base"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:base fg:yellow)[ ]($style)"
style = "bg:none fg:base"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "\\${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[took ](bg:base fg:blue bold)$duration](bg:base fg:text)[ ]($style)"
disabled = false
style = "bg:none fg:base"

[palettes.github_dark]
red = "#CA3B37"
yellow = "#DBAA3F"
green = "#57AB5A"
blue = "#4491F5"
text = "#E6EDF3"
base = "#161B22"
